BMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import  views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^adminstrator/',include('adminstrator.urls')),
    url(r'^faculty/',include('faculty.urls')),
    url(r'^student/',include('student.urls')),
]

student/urls.py
from django.conf.urls import url
from . import views

app_name = 'student'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^regsuccess/$', views.regs, name='success'),
    url(r'^login/$',views.slogin,name='slogin'),
    url(r'^studenthome/$',views.shome,name='shome'),
    url(r'^logout/$',views.stud_logout,name='stud_logout'),
    url(r'^forgotpassword/$',views.fpass,name='fpass'),
    url(r'^emailsent/$',views.email,name='email')
    ]

student/models.py
from django.db import models

# Create your models here.

COURSES = (('SE', 'Software Engineering'),
            ('BIS', 'Business Information Systems'),
            ('DBMS', 'Database Management Systems'),
            ('TC', 'Technical Communication'),
            ('CN', 'Computer Networks'),
            ('LP', 'Language Processors'),
            )


class RegisterStudent(models.Model):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(unique=True)
    studid = models.IntegerField(unique=True)
    password = models.CharField(max_length=20)
    bluetooth_addr = models.CharField(max_length=30, unique=True)
    approval = models.BooleanField(default=False)

    def __str__(self):
        return  self.username


class StudentCourses(models.Model):
    studentid = models.ForeignKey(RegisterStudent,on_delete=models.CASCADE)
    course = models.CharField(max_length=50)

    def __str__(self):
        return  self.course

student/views.py
from django.shortcuts import render, redirect
import math
from django.conf import settings
from django.contrib import messages
from .models import RegisterStudent
from .models import StudentCourses
from faculty.models import Attendance_sheet,Register
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
import bluetooth
from datetime import date



def home(request):
    if request.method == 'POST':
        bad = request.POST['baddr']
        mail = request.POST['email']
        sreg = RegisterStudent.objects.filter(bluetooth_addr=bad)
        if sreg.count() == 0:
            sreg = RegisterStudent.objects.filter(email=mail)
            if sreg.count() == 0:
                register = RegisterStudent(
                                    username=request.POST['username'],
                                    email=mail,
                                    studid=request.POST['sid'],
                                    password=request.POST['password'],
                                    bluetooth_addr=bad,
                                    approval=False
                )
                register.save()
                courses = request.POST.getlist('courses')
                for course in courses:
                    sc = StudentCourses(studentid=register,course=course)
                    sc.save()
                return redirect('student:success')
            else:
                nearby_devices = bluetooth.discover_devices()
                dict = {}
                for x in nearby_devices:
                    dict[x] = bluetooth.lookup_name(x)
                return render(request, 'student/register_form.html',
                              {'dict': dict, 'errors':'Email Id already exists'})
        else:
            nearby_devices = bluetooth.discover_devices()
            dict = {}
            for x in nearby_devices:
                dict[x] = bluetooth.lookup_name(x)
            return render(request, 'student/register_form.html', {'dict': dict,'errors': 'Bluetooth Ip address has been already registered'})
    else:
        # First time the form is displayed to student
        nearby_devices = bluetooth.discover_devices()
        dict = {}
        for x in nearby_devices:
            dict[x] = bluetooth.lookup_name(x)
        return render(request, 'student/register_form.html',{'dict': dict})



def slogin(request):
    if request.method == "POST":
        studentid = request.POST['sid']
        password = request.POST['password']
        student = RegisterStudent.objects.filter(studid=studentid, password=password)
        if student.count() == 1:
            for s in student:
                request.session['id'] = s.pk
            r = RegisterStudent.objects.filter(studid=studentid, password=password,approval=True)
            if r.count() == 1:
                return redirect('student:shome')
            else:
                return render(request, 'student/login.html',{'error':'Not Approved Yet'})
        else:
            return render(request, 'student/login.html', {'error': 'Wrong Credentials'})
    else:
        return render(request, 'student/login.html')

def regs(request):
    return render(request,'student/regsuccess.html')

def shome(request):
    if 'id' in request.session:
        student = RegisterStudent.objects.get(pk=request.session['id'])
        s = Attendance_sheet.objects.filter(sid=student.studid)
        sc = StudentCourses.objects.filter(studentid=student)
        f = Register.objects.filter(approval=True)
        ca = {}
        for i in sc:
            curr_day = Attendance_sheet.objects.filter(sid=student.studid,date=date.today(),course=i.course)
            curr = Attendance_sheet.objects.filter(date=date.today(),course=i.course)
            if curr.count() > 0:
                if curr_day.count() == 1:
                    ca[i.course] = 'P'
                else:
                    ca[i.course] = 'A'
            else:
                ca[i.course] = 'N'

        dict = {}
        p = {}
        for i in sc:
            k = Attendance_sheet.objects.filter(sid=student.studid,course=i.course)
            dict[i.course] = k.count()
            s1 = Register.objects.filter(approval=True, course=i.course)
            if s1.count() > 0:
                t = Register.objects.get(approval=True, course=i.course)
                if t.count != 0:
                    p[i.course] = math.ceil((k.count()/t.count)*100)
                else:
                    p[i.course] = 0
            else:
                p[i.course] = 0
        return render(request,'student/studenthome.html',{'student':student,'f':f,'dict':dict,'p':p,'ca':ca})
    else:
        return redirect('student:slogin')

def stud_logout(request):
    del request.session['id']
    return redirect('student:slogin')

def fpass(request):
    return render(request,'student/fpassword.html')

def email(request):
    mail = request.POST['email']
    student = RegisterStudent.objects.get(email=mail)
    message = 'password is'+ student.password
    from_mail = settings.EMAIL_HOST_USER
    send_mail('Forgot password',message,from_mail, [mail])
    return render(request,'student/fpassword.html',{'error':'Password was sent to your registered Email ID'})

student/templates/student/base.html
{% extends 'base.html' %}
{% block title %}Student Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'student:shome' %}">Home</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <a href="{% url 'student:stud_logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}

{% endblock %}

student/templates/student/form_template.html
{% for field in register_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

student/templates/student/fpassword.html
{% extends 'base.html' %}
{% block title %}Student Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <li class="active">
                        <a href="{% url 'student:home' %}" >
                             Register
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'student:slogin' %}" >
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}
    <div class="col-md-4 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Forgot Password
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" action="{% url 'student:email' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-2 col-md-offset-1 control-label">Email</label>
                            <div class="col-md-8">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email Id" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-5">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

student/templates/student/login.html
{% extends 'base.html' %}
{% block title %}Student Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <li class="active">
                        <a href="{% url 'student:home' %}" >
                             Register
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'student:slogin' %}" >
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}
    <div class="col-md-4 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Student Login
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sid" class="col-md-2 col-md-offset-1 control-label">Student Id</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="sid" name="sid" placeholder="Student ID" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="pass" class="col-md-2 col-md-offset-1 control-label">Password</label>
                            <div class="col-md-8">
                                <input type="password" class="form-control" id="pass" name="password" placeholder="Password" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-3">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                            <div class="col-md-8 col-md-offset-3">
                                <a href="{% url 'student:fpass' %}">Forgot Password</a>
                            </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

student/templates/student/register_form.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'student:home' %}" >
                             Register
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'student:slogin' %}" >
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}
 <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Student Registration
            </div>
            <div class="panel-body">
                {% csrf_token %}
                    {% if errors %}
                        <p><strong>{{ errors }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="username" class="col-md-2 col-md-offset-1 control-label">Username</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="username" name="username" placeholder="Username" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-2 col-md-offset-1 control-label">Email</label>
                            <div class="col-md-8">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email Id" required/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sid" class="col-md-2 col-md-offset-1 control-label">Student Id</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="sid" name="sid" placeholder="Student Id" required/>
                            </div>
                        </div>


                         <div class="form-group">
                            <label for="pass" class="col-md-2 col-md-offset-1 control-label">Password</label>
                            <div class="col-md-8">
                                <input type="password" class="form-control" id="pass" name="password" placeholder="Password" required/>
                            </div>
                        </div>
                            <label for="course" class="col-md-2 col-md-offset-1 control-label">Courses</label>
                            <div class="checkbox">
                                <label><input type="checkbox"  value="SE" id="course" name="courses">SE</label>

                                <label><input type="checkbox" value="DBMS" id="course" name="courses" >DBMS</label>

                                <label><input type="checkbox" value="CN" id="course" name="courses" >CN</label>

                                <label><input type="checkbox" value="LP" id="course" name="courses">LP</label>

                                <label><input type="checkbox" value="TC" id="course" name="courses">TC</label>

                                <label><input type="checkbox" value="BIS" id="course" name="courses">BIS</label>
                            <br>
                            </div>
                        <br>
                        <div class="form-group">
                            <label for="baddr" class="col-md-3 col-md-offset-1">Bluetooth Address</label>
                            <div class="col-md-5">
                                <select class="form-control" id="baddr"  name="baddr">
                                    <option selected="selected">Select Bluetooth Address</option>
                                    {% for key,value in dict.items  %}
                                        <option value="{{ key }}">{{ key }} - {{ value }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <br>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                      </fieldset>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'student:slogin' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
{% endblock %}

student/templates/student/regsuccess.html
{% extends 'base.html' %}
{% block title %}Registration Success{% endblock %}
{%block body %}
<h3>Registration Successful</h3>
{% endblock %}

student/templates/student/studenthome.html
{% extends 'student/base.html' %}
{% block title %}Student Home{% endblock %}
{% block body %}
    <h3>Welcome {{ student.username }}</h3>
    <br>
    <div class="col-md-4 col-md-offset-1">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Total Attendance
            </div>
            <div class="panel-body">
                 <table class="table table-hover">
            <thead>
                <tr>
                    <th>Course</th>
                    <th>Classes Attended</th>
                    <th>classes Conducted</th>
                    <th>Percentage</th>
                    <th> >75% </th>
                </tr>
            </thead>
            <tbody>
            {% for key,value in dict.items %}
                <tr>
                <td>
                    {{ key }}
                </td>
                <td>
                    {{ value }}
                </td>
                <td>
                    {% for j in f %}
                            {% if key == j.course %}
                                {{ j.count }}
                            {% endif %}
                        {% endfor %}
                </td>
                <td>
                    {% for k,v in p.items %}
                        {% if key == k %}
                            {{ v }}
                            <td>
                            {% if v < 75 %}
                                <p class="text-danger"><strong>Less than 75%</strong></p>
                                {% endif %}
                            </td>
                        {% endif %}
                        {% endfor %}
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-md-offset-1">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Current Day Attendance
            </div>
            <div class="panel-body">
                 <table class="table table-hover">
            <thead>
                <tr>
                    <th>Course</th>
                    <th>Present(P)/Absent(A)/Class Not Taken(N)</th>
                </tr>
            </thead>
            <tbody>
            {% for key,value in ca.items %}
                <tr>
                <td>
                    {{ key }}
                </td>
                <td>
                    <div class="col-md-offset-3">
                    {{ value }}
                    </div>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
            </div>
        </div>
    </div>
{% endblock %}