BMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import  views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^adminstrator/',include('adminstrator.urls')),
    url(r'^faculty/',include('faculty.urls')),
    url(r'^student/',include('student.urls')),
]

faculty/urls.py
from django.conf.urls import  url
from . import  views

app_name = 'faculty'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^regsuccess/$',views.regs,name='success'),
    url(r'^login/$',views.flogin,name='flogin'),
    url(r'^facultyhome/$',views.fachome,name='fachome'),
    url(r'^attendance/$',views.attendance,name='attendance'),
    url(r'^choosedate/$',views.sheet,name='sheet'),
    url(r'^editsheet/$',views.editsheet,name='editsheet'),
    url(r'^attendancesheet/$',views.viewsheet,name='viewsheet'),
    url(r'edit/$',views.view,name='view'),
    url(r'^logout/$',views.fac_logout,name='fac_logout'),
    url(r'^fullsheet/$', views.fullsheet, name='fullsheet')

]

faculty/models.py
from django.db import models
from datetime import date

# Create your models here.


COURSES = (('SE', 'Software Engineering'),
            ('BIS', 'Business Information Systems'),
            ('DBMS', 'Database Management Systems'),
            ('TC', 'Technical Communication'),
            ('CN', 'Computer Networks'),
            ('LP', 'Language Processors'),
            )

class Register(models.Model):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(unique=True)
    factid = models.IntegerField(null=True)
    course= models.CharField(max_length=4,choices=COURSES,unique=True)
    count = models.IntegerField(default=0)
    password = models.CharField(max_length=20)
    approval = models.BooleanField(default=False)

    def __str__(self):
        return  self.username


class Attendance_sheet(models.Model):
    factid = models.IntegerField()
    course = models.CharField(max_length=30)
    date = models.DateField(default=date.today)
    sid = models.IntegerField()

faculty/forms.py
from django import forms

from .models import Register

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Register
        fields = ['username', 'email', 'course','password']

faculty/views.py
import bluetooth
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from .models import Register,Attendance_sheet
from .forms import RegisterForm
from datetime import date
from student.models import RegisterStudent,StudentCourses
from django.core.urlresolvers import reverse
import math

# Create your views here.


def home(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            register = Register(username=request.POST['username'],
                                email=request.POST['email'],
                                factid=None,
                                course=request.POST['course'],
                                password=request.POST['password'],
                                approval=False
                                )
            register.save()
            return redirect('faculty:success')
        else:
            error = 'Please correct the errors below.'
            return render(request, 'faculty/register_form.html', {
                'error': error,
                'register_form': register_form})
    else:
        # First time the form is displayed to student
        register_form = RegisterForm()
        return render(request, 'faculty/register_form.html', {
            'register_form': register_form
        })




def regs(request):
    return render(request,'faculty/regsuccess.html')

def flogin(request):
    if request.method == "POST":
        Email = request.POST['email']
        password = request.POST['password']
        registers = Register.objects.filter(email=Email, password=password)
        if registers.count() == 1:
            for register in registers:
                request.session['id'] = register.pk
            r = Register.objects.filter(email=Email, password=password,approval=True)
            if r.count() == 1:
                return redirect('faculty:fachome')
            else:
                return render(request, 'faculty/login.html',{'error':'Not Approved Yet'})
        else:
            return render(request, 'faculty/login.html', {'error': 'Wrong Credentials'})
    else:
        return render(request, 'faculty/login.html')


def fachome(request):
    if 'id' in request.session:
        register = Register.objects.get(pk=request.session['id'])
        s = RegisterStudent.objects.filter(approval=True)
        return render(request, 'faculty/facultyhome.html', {'register': register,'s':s})
    else:
        return redirect('faculty:flogin')

def fac_logout(request):
    del request.session['id']
    return redirect('faculty:flogin')


def attendance(request):
    if 'id' in request.session:
        faculty = Register.objects.get(pk=request.session['id'])
        nearby_devices = bluetooth.discover_devices()
        students = StudentCourses.objects.filter(course=faculty.course,studentid__approval=True)
        s1 = Attendance_sheet.objects.filter(course=faculty.course,date=date.today())
        if s1.count()==0:
            faculty.count=faculty.count+1
            faculty.save()
        for i in students:
            for j in nearby_devices:
                if i.studentid.bluetooth_addr==j:
                    s1 = Attendance_sheet.objects.filter(factid=faculty.factid,course=i.course,date=date.today(),sid=i.studentid.studid)
                    if s1.count()==0:
                        s = Attendance_sheet(factid=faculty.factid, course=i.course, date=date.today(),sid=i.studentid.studid)
                        s.save()
        return render(request, 'faculty/attendance.html',{'nearby_devices':nearby_devices,'faculty':faculty,'students':students})
    else:
        return redirect('faculty:flogin')

def viewsheet(request):
    if 'id' in request.session:
        faculty = Register.objects.get(pk=request.session['id'])
        if request.method == 'POST':
            d = request.POST.get('date')
            sheet = Attendance_sheet.objects.filter(course=faculty.course,date=d)
            students =RegisterStudent.objects.filter(approval=True)
            if sheet.count()>0:
                return render(request, 'faculty/viewsheet.html',{'sheet':sheet,'students':students})
            else:
                return render(request,'faculty/viewsheet.html',{'messages':'No records present'})
        else:
            return render(request, 'faculty/sheet.html')
    else:
        return redirect('faculty:flogin')

def sheet(request):
    if 'id' in request.session:
        return render(request, 'faculty/sheet.html')
    else:
        return redirect('faculty:flogin')


def editsheet(request):
    if 'id' in request.session:
        faculty = Register.objects.get(pk=request.session['id'])
        faculty = Register.objects.get(pk=request.session['id'])
        all_students = StudentCourses.objects.filter(course=faculty.course, studentid__approval=True)
        students = Attendance_sheet.objects.filter(course=faculty.course, date=date.today())
        dict = {}
        pdict = {}
        f = 0
        for i in all_students:
            f = 0
            for j in students:
                if i.studentid.studid == j.sid:
                    f = 1
            if f == 1:
                pdict[i.studentid.studid] = i.studentid.username
            else:
                dict[i.studentid.studid] = i.studentid.username
        return render(request, 'faculty/editsheet.html', {'dict': dict, 'pdict': pdict})
    else:
        return redirect('faculty:flogin')

def view(request):
    if 'id' in request.session:
        faculty = Register.objects.get(pk=request.session['id'])
        s = Attendance_sheet.objects.filter(course=faculty.course, date=date.today(), factid=faculty.factid)
        s.delete()
        print('faculty course:'+faculty.course)
        students = request.POST.getlist('sid')
        for j in students:
            s1 = Attendance_sheet(factid=faculty.factid, course=faculty.course, sid=j)
            s1.save()
        return render(request,'faculty/edited.html')
    else:
        return redirect('faculty:flogin')


def fullsheet(request):
    if 'id' in request.session:
        faculty = Register.objects.get(pk=request.session['id'])
        s = Attendance_sheet.objects.filter(course=faculty.course, factid=faculty.factid)
        s1 = StudentCourses.objects.filter(studentid__approval=True, course=faculty.course)
        dict  = {}
        for i in s1:
            k = Attendance_sheet.objects.filter(course=faculty.course, factid=faculty.factid, sid=i.studentid.studid)
            if faculty.count > 0:
                dict[i.studentid.studid] = math.ceil((k.count() / faculty.count) * 100)
            else:
                dict[i.studentid.studid] = 0
            print(i.studentid.studid)
            print(dict[i.studentid.studid])
        if s.count() == 0:
            return render(request, 'faculty/fullsheet.html', {'dict': dict, 'faculty': faculty, 's1': s1, 'messages': 'No records present'})
        else:
            return render(request, 'faculty/fullsheet.html',{'dict': dict, 'faculty': faculty, 's1': s1})
    else:
        return redirect('faculty:flogin')

faculty/templates/faculty/attendance.html
{% extends 'faculty/base.html' %}
{% block title %}Attendance{% endblock %}
{% block body %}
    <div class="container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Student Id</th>
                    <th>Username</th>
                    <th>Bluetooth Address</th>
                </tr>
            </thead>
            <tbody>
    {% for i in students %}
        {% for j in nearby_devices %}
            {% if i.studentid.bluetooth_addr == j %}
                <tr>
                    <td> {{ i.studentid.studid }}</td>
                    <td>{{ i.studentid.username }}</td>
                <td>{{ i.studentid.bluetooth_addr }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

faculty/templates/faculty/base.html
{% extends 'base.html' %}
{% block title %}Student Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'faculty:fachome' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <a href="{% url 'faculty:fac_logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}

{% endblock %}

faculty/templates/faculty/edited.html
{% extends 'faculty/base.html' %}
{% block title %}Successfully Edited{% endblock %}
{% block body %}
<h3>Edited</h3>
{% endblock %}

faculty/templates/faculty/editsheet.html
{% extends 'faculty/base.html' %}
{% block title %}Attendance Sheet{% endblock %}
{% block head %}

{% endblock %}
{% block body %}
<div class="col-md-5 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Edit Sheet
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" action="{% url 'faculty:view' %}"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="checkbox col-md-offset-3">
                                {% for key,value in pdict.items %}
                                    <h4><label><input type="checkbox" class="check" value="{{ key }}"  name="sid" checked="checked" >{{ key }} - {{ value }}</label></h4><br>
                                {% endfor %}
                                {% for key,value in dict.items %}
                                    <h4><label><input type="checkbox" class="check" value="{{ key }}"  name="sid">{{ key }} - {{ value }}</label></h4><br>
                                {% endfor %}
                                    <h4><label><input type="checkbox" class="check" id="checkAll">Check All</label></h4>
                            <br>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-5">
                                <button type="submit" class="btn btn-primary">
                                    Edit
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
   <script>
        $("#checkAll").click(function ()
        {
        $(".check").prop('checked', $(this).prop('checked'));
        });
    </script>
{% endblock %}

faculty/templates/faculty/facultyhome.html
{% extends 'faculty/base.html' %}
{% block title %}Faculty Home{% endblock %}
{% block body %}
    <h1>Welcome {{ register }}</h1>
    <br>
    <h3 style="color: #d43f3a ">
        <div class="col-md-offset-4">
            Number of Students Enrolled for your Course: {{ s.count }}
        </div>
    </h3>
    <br>
    &nbsp;<form class="form-horizontal" role="form" action="{% url 'faculty:attendance' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
           &nbsp;&nbsp;<button type="submit" class="btn">Take Attendance</button>
        </div>
    </form>
    <br>
    <form class="form-horizontal" role="form" action="{% url 'faculty:sheet' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn">View Attendance Sheet</button>
    </form>
    <br>
    <br>
    <form class="form-horizontal" role="form" action="{% url 'faculty:editsheet' %}"  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn">Edit Attendance sheet</button>
    </form>
    <br>
    <br>
    <form class="form-horizontal" role="form" action="{% url 'faculty:fullsheet' %}"  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn">View whole Attendance sheet</button>
    </form>


{% endblock %}

faculty/templates/faculty/form_template.html
{% for field in register_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

faculty/templates/faculty/fullsheet.html
{% extends 'faculty/base.html' %}
{% block title %}Full Attendance Sheet{% endblock %}
{% block body %}
    <div class="container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th><h3>Student Id</h3></th>
                    <th><h3>Username</h3></th>
                    <th><h3>Percentage</h3></th>
                </tr>
            </thead>
            <tbody>
             {% if messages %}
                 <h4 class="text-danger">{{ messages }}</h4>
             {% else%}
                                    &nbsp;
             {% endif %}
            {% for i in s1 %}
              {% for key,value in dict.items %}
                  {% if key == i.studentid.studid %}
                      {% if value < 75 %}
                <tr class="danger">
                    <td>
                        <h4>{{ i.studentid.studid }}</h4>
                    </td>
                    <td>
                        <h4>{{ i.studentid.username }}</h4>
                    </td>
                    <td >

                        <h4>{{ value }}</h4>
                    </td>
                </tr>
                      {% else %}
                          <tr>
                            <td>
                                <h4>{{ i.studentid.studid }}</h4>
                            </td>
                            <td>
                                <h4>{{ i.studentid.username }}</h4>
                            </td>
                            <td >

                                                <h4>{{ value }}</h4>
                            </td>
                          </tr>
                                    {% endif %}
                                {% endif %}
                                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

faculty/templates/faculty/login.html
{% extends 'base.html' %}
{% block title %}Faculty Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <li class="active">
                        <a href="{% url 'faculty:home' %}" >
                             Register
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'faculty:flogin' %}" >
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}
    <div class="col-md-4 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Faculty Login
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-2 col-md-offset-1 control-label">Email</label>
                            <div class="col-md-8">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email Id" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="pass" class="col-md-2 col-md-offset-1 control-label">Password</label>
                            <div class="col-md-8">
                                <input type="password" class="form-control" id="pass" name="password" placeholder="Password" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-5">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

faculty/templates/faculty/register_form.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'faculty:home' %}" >
                             Register
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'faculty:flogin' %}" >
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Login
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}
 <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Faculty Registration
            </div>
            <div class="panel-body">
                    {% if error %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'faculty/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'faculty:flogin' %}">Click here</a> to log in.
                </div>
            </div>
            <div>

            </div>
        </div>
    </div>

</div>
{% endblock %}

faculty/templates/faculty/regsuccess.html
{% extends 'base.html' %}
{% block title %}Registration Success{% endblock %}
{%block body %}
<h3>Registration Successfull</h3>
{% endblock %}

faculty/templates/faculty/sheet.html
{% extends 'faculty/base.html' %}
{% block title %}Attendance Sheet{% endblock %}
{% block body %}
    <div class="col-md-4 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Attendance Sheet
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" action="{% url 'faculty:viewsheet' %}"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="date" class="col-md-2 col-md-offset-1 control-label">Date</label>
                            <div class="col-md-8">
                                <input type="date" class="form-control" id="date" name="date" placeholder="Date" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-5">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

faculty/templates/faculty/viewsheet.html
{% extends 'faculty/base.html' %}
{% block title %}Attendance{% endblock %}
{% block body %}
    <div class="container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Student Id</th>
                    <th>Username</th>
                </tr>
            </thead>
            <tbody>
             {% if messages %}
                 <h3 class="text-danger">{{ messages }}</h3>
             {% else%}
                                    &nbsp;
             {% endif %}
    {% for i in sheet %}
        {% for j in students %}
            {% if i.sid == j.studid %}
                <tr>
                    <td> {{ i.sid }}</td>
                    <td>{{ j.username }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}