BMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import  views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^adminstrator/',include('adminstrator.urls')),
    url(r'^faculty/',include('faculty.urls')),
    url(r'^student/',include('student.urls')),
]

adminstrator/urls.py
from django.conf.urls import url
from . import views

app_name = 'adminstrator'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^adminhome/$', views.adminhome, name='adminhome'),
    url(r'^logoutadmin/$',views.logoutadmin,name='logoutadmin'),
    url(r'^fapprove/$',views.fapproval,name='fapproval'),
    url(r'sapprove/$',views.sapproval,name='sapproval')
    ]

adminstrator/models.py
from django.db import models
from student.models import COURSES
# Create your models here.

adminstrator/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login,logout
from faculty.models import Register
from student.models import StudentCourses,RegisterStudent
from django.core.urlresolvers import reverse



# Create your views here.



def home(request):
        #after login to admin
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('adminstrator:adminhome')
                else:
                    return render(request, 'adminstrator/login.html', {'error': 'Your account has been disabled'})
            else:
                return render(request, 'adminstrator/login.html', {'error': 'Invalid login'})
        #before login
        return render(request, 'adminstrator/login.html')

def adminhome(request):
    if not request.user.is_authenticated():
        return redirect('adminstrator:home')
    else:
        registers = Register.objects.filter(approval=False)
        students = RegisterStudent.objects.filter(approval=False)
        courses = StudentCourses.objects.filter(studentid__approval=False)
        return render(request, 'adminstrator/adminhome.html',{'registers': registers,'students':students,'courses':courses})

def logoutadmin(request):
    #logging out
    logout(request)
    return redirect('adminstrator:home')

def fapproval(request):
    course = request.POST['course']
    id = request.POST['fid']
    status = request.POST['status']
    if status == 'approve':
        if id != '-1':
            regs = Register.objects.filter(factid=id)
            if regs.count() == 1:
                registers = Register.objects.filter(approval=False)
                students = RegisterStudent.objects.filter(approval=False)
                courses = StudentCourses.objects.filter(studentid__approval=False)
                return render(request,'adminstrator/adminhome.html',{'error' : 'Faculty id was already taken'
                    ,'registers': registers,'students':students,'courses':courses})
            elif regs.count() == 0:
                reg = get_object_or_404(Register,course=course)
                reg.approval = True
                reg.factid = id
                reg.save()
                freg = Register.objects.get(course=course)
                return render(request , 'adminstrator/fapproved.html' , {'freg': freg})
        else:
            registers = Register.objects.filter(approval=False)
            students = RegisterStudent.objects.filter(approval=False)
            courses = StudentCourses.objects.filter(studentid__approval=False)
            return render(request, 'adminstrator/adminhome.html',
                          {'error': 'Faculty id was Not given', 'registers': registers,'students':students,'courses':courses})
    else:
        dreg = Register.objects.get(course=course)
        dreg.delete()
        registers = Register.objects.filter(approval=False)
        students = RegisterStudent.objects.filter(approval=False)
        courses = StudentCourses.objects.filter(studentid__approval=False)
        return render(request,'adminstrator/adminhome.html',{'registers':registers,'students':students,'courses':courses})



def sapproval(request):
    sid = request.POST['sid']
    status = request.POST['status']
    if status == 'approve':
        s = get_object_or_404(RegisterStudent,studid=sid)
        s.approval=True
        s.save()
        registers = Register.objects.filter(approval=False)
        students = RegisterStudent.objects.filter(approval=False)
        courses = StudentCourses.objects.filter(studentid__approval=False)
        return render(request,'adminstrator/adminhome.html',{'registers':registers,
                                                             'students':students,'courses':courses,'error_messages':'Approved'})
    else:
        sreg = RegisterStudent.objects.get(studid=sid)
        sreg.delete()
        registers = Register.objects.filter(approval=False)
        students = RegisterStudent.objects.filter(approval=False)
        courses = StudentCourses.objects.filter(studentid__approval=False)
        return render(request,'adminstrator/adminhome.html',{'registers':registers,'students':students,'courses':courses})

adminstrator/templates/adminstrator/adminhome.html
{% extends 'adminstrator/base.html' %}
{% block title %}Admin Home{% endblock %}
{% block body %}
    <h1>Welcome admin!</h1><br>
        <div class="col-md-11 ">
        <div class="panel panel-default">
            <div class="panel-heading">
                        Pending Faculty Approvals
            </div>
            <div class="panel-body">
                <div class="container">
                {% if error %}
                    <h3 class="text-danger">{{ error }}</h3>
                {% else%}
                                    &nbsp;
                {% endif %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Faculty Name</th>
            <th>Course</th>
            <th>Faculty Id</th>
              <th>Approval</th>
              <th>Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for register in registers %}
                <form class="form-horizontal" role="form"  action="{% url 'adminstrator:fapproval' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                          <tr>
                            <td>
                                   {{ register.username }}
                            </td>
                            <td>
                                <div class="form-group">
                                       <input type="text" class="form-control" value="{{ register.course }}" id="course" name="course" />
                                </div>
                            </td>
                            <td>
                                  <div class="form-group">
                                      <input type="number" class="form-control" value="-1" id="fid" name="fid"  />
                                  </div>
                            </td>
                              <td>
                                    <div class="form-group">
                                        <input type="radio" name="status" value="approve" checked="checked">
                                            Approve
                                        </input>
                                    </div>
                              </td>
                              <td>
                                    <div class="form-group">
                                        <input type="radio" name="status" value="delete">
                                            Delete
                                        </input>
                                    </div>
                              </td>
                              <td>
                                  <div class="form-group">
                                    <div class="col-md-8 col-md-offset-5">
                                        <button type="submit" class="btn btn-primary">
                                            Apply
                                        </button>
                                     </div>
                                  </div>
                              </td>
                          </tr>
                        </fieldset>
                </form>
                {% endfor %}
        </tbody>
      </table>
    </div>
    </div>
        </div>
    </div>

    <div class="col-md-11 ">
        <div class="panel panel-default">
            <div class="panel-heading">
                        Pending Student Approvals
            </div>
            <div class="panel-body">
                <div class="container">
                {% if error_messages %}
                    <h3 class="text-danger">{{ error_messages }}</h3>
                {% else%}
                                    &nbsp;
                {% endif %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Student Name</th>
            <th>Bluetooth Address</th>
            <th>Student Id</th>
              <th>Courses</th>
              <th>Approval</th>
              <th>Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for student in students %}
                <form class="form-horizontal" role="form"  action="{% url 'adminstrator:sapproval' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                          <tr>
                            <td>
                                   {{ student.username }}
                            </td>
                              <td>
                                   {{ student.bluetooth_addr }}
                            </td>
                            <td>
                                <div class="form-group">
                                       <input type="number" class="form-control" value="{{ student.studid }}" id="sid" name="sid" />
                                </div>
                            </td>
                            <td>
                                  {% for i in courses %}
                                      {% if i.studentid == student %}
                                          {{ i.course }}
                                      {% endif %}
                                      {% endfor %}
                            </td>
                              <td>
                                    <div class="form-group">
                                        <input type="radio" name="status" value="approve" checked="checked">
                                            Approve
                                        </input>
                                    </div>
                              </td>
                              <td>
                                    <div class="form-group">
                                        <input type="radio" name="status" value="delete">
                                            Delete
                                        </input>
                                    </div>
                              </td>
                              <td>
                                  <div class="form-group">
                                    <div class="col-md-8 col-md-offset-5">
                                        <button type="submit" class="btn btn-primary">
                                            Apply
                                        </button>
                                     </div>
                                  </div>
                              </td>
                          </tr>
                        </fieldset>
                </form>
                {% endfor %}
        </tbody>
      </table>
    </div>
    </div>
        </div>
    </div>
{% endblock %}

adminstrator/templates/adminstrator/base.html
{% extends 'base.html' %}
{% block title %}Admin Login{% endblock %}
{% block navbar %}
    <nav id="mainNav" class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="btn-primary navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'adminstrator:adminhome' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <a href="{% url 'adminstrator:logoutadmin' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block body %}

{% endblock %}

adminstrator/templates/adminstrator/fapproved.html
{% extends 'adminstrator/base.html' %}
{% block title %}Approved{% endblock %}
 {% csrf_token %}
{%block body %}
<h3>Faculty with Username {{ freg  }} has been Approved </h3>
{% endblock %}

adminstrator/templates/adminstrator/login.html
{% extends 'base.html' %}
{% block title %}Admin Login{% endblock %}
{% block body %}
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Admin Login
            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                {% if error %}
                                    <h3 class="text-danger">{{ error }}</h3>
                                {% else%}
                                    &nbsp;
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="username" class="col-md-2 col-md-offset-1 control-label">Username</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="username" name="username" placeholder="username" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="pass" class="col-md-2 col-md-offset-1 control-label">Password</label>
                            <div class="col-md-8">
                                <input type="password" class="form-control" id="pass" name="password" placeholder="Password" required/>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-8 col-md-offset-5">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}